In [3]:
!pip install numpy
import numpy as np
!pip install gym
import gym
import random
import time
from IPython.display import clear_output
from gym.envs.toy_text.frozen_lake import generate_random_map


[notice] A new release of pip is available: 23.1.2 -> 23.2.1
[notice] To update, run: C:\Users\clayb\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

[notice] A new release of pip is available: 23.1.2 -> 23.2.1
[notice] To update, run: C:\Users\clayb\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


                                              0.0/721.7 kB ? eta -:--:--
                                              10.2/721.7 kB ? eta -:--:--
     -                                     30.7/721.7 kB 435.7 kB/s eta 0:00:02
     -                                     30.7/721.7 kB 435.7 kB/s eta 0:00:02
     -                                     30.7/721.7 kB 435.7 kB/s eta 0:00:02
     -                                     30.7/721.7 kB 435.7 kB/s eta 0:00:02
     --                                    41.0/721.7 kB 115.5 kB/s eta 0:00:06
     ---                                   61.4/721.7 kB 172.4 kB/s eta 0:00:04
     ---                                   61.4/721.7 kB 172.4 kB/s eta 0:00:04
     ----                                  81.9/721.7 kB 183.3 kB/s eta 0:00:04
     ----                                  92.2/721.7 kB 180.8 kB/s eta 0:00:04
     ----                                  92.2/721.7 kB 180.8 kB/s eta 0:00:04
     ----                                  92.2/721.7

In [4]:
env = gym.make('FrozenLake-v1', render_mode='ansi')

In [5]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n

q_table = np.zeros((state_space_size, action_space_size))

print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [7]:
def load_frozen_lake(desc=None, map_name=None, is_slippery=False):
    """
    Load the FrozenLake environment from OpenAI's gym.

    Parameters:
    desc -- None or a list of lists containing a custom
    description of the map to load for the environment
    map_name -- None or a string containing the pre-made map to load
    is_slippery -- a boolean to determine if the ice is slippery

    If both desc and map_name are None, the environment will
    load a randomly generated 8x8 map.

    Returns:
    The FrozenLake environment.
    """
    if desc is None and map_name is None:
        desc = generate_random_map(size=8)

    return gym.make('FrozenLake-v1', desc=desc,
                    map_name=map_name, is_slippery=is_slippery)

In [8]:
np.random.seed(0)
env = load_frozen_lake()
print(env.desc)
print(env.P[0][0])
env = load_frozen_lake(is_slippery=True)
print(env.desc)
print(env.P[0][0])
desc = [['S', 'F', 'F'], ['F', 'H', 'H'], ['F', 'F', 'G']]
env = load_frozen_lake(desc=desc)
print(env.desc)
env = load_frozen_lake(map_name='4x4')
print(env.desc)

[[b'S' b'F' b'F' b'F' b'F' b'F' b'F' b'H']
 [b'H' b'F' b'F' b'F' b'F' b'H' b'F' b'F']
 [b'F' b'H' b'F' b'H' b'H' b'F' b'F' b'F']
 [b'F' b'F' b'F' b'H' b'F' b'F' b'F' b'F']
 [b'F' b'F' b'F' b'F' b'F' b'F' b'H' b'F']
 [b'F' b'F' b'F' b'F' b'F' b'F' b'F' b'F']
 [b'F' b'F' b'F' b'F' b'H' b'F' b'F' b'F']
 [b'F' b'F' b'F' b'F' b'F' b'F' b'F' b'G']]
[(1.0, 0, 0.0, False)]
[[b'S' b'F' b'H' b'F' b'H' b'F' b'H' b'F']
 [b'H' b'F' b'F' b'F' b'F' b'F' b'F' b'F']
 [b'F' b'F' b'F' b'F' b'F' b'F' b'F' b'F']
 [b'F' b'H' b'F' b'F' b'F' b'F' b'F' b'F']
 [b'F' b'F' b'H' b'F' b'F' b'F' b'F' b'H']
 [b'F' b'F' b'F' b'F' b'F' b'H' b'F' b'H']
 [b'F' b'F' b'H' b'F' b'H' b'F' b'H' b'F']
 [b'F' b'F' b'H' b'F' b'F' b'F' b'F' b'G']]
[(0.3333333333333333, 0, 0.0, False), (0.3333333333333333, 0, 0.0, False), (0.3333333333333333, 8, 0.0, True)]
[[b'S' b'F' b'F']
 [b'F' b'H' b'H']
 [b'F' b'F' b'G']]
[[b'S' b'F' b'F' b'F']
 [b'F' b'H' b'F' b'H']
 [b'F' b'F' b'F' b'H']
 [b'H' b'F' b'F' b'G']]


In [9]:
def q_init(env):
    """Initialize Q-table to zeros."""
    return np.zeros([env.observation_space.n, env.action_space.n])

In [10]:
env = load_frozen_lake()
Q = q_init(env)
print(Q.shape)
env = load_frozen_lake(is_slippery=True)
Q = q_init(env)
print(Q.shape)
desc = [['S', 'F', 'F'], ['F', 'H', 'H'], ['F', 'F', 'G']]
env = load_frozen_lake(desc=desc)
Q = q_init(env)
print(Q.shape)
env = load_frozen_lake(map_name='4x4')
Q = q_init(env)
print(Q.shape)

(64, 4)
(64, 4)
(9, 4)
(16, 4)


In [11]:
def epsilon_greedy(Q, state, epsilon):
    """Epsilon-greedy policy."""
    if random.uniform(0, 1) < epsilon:
        action = env.action_space.sample()  # Explore action space
    else:
        action = np.argmax(Q[state])  # Exploit learned values
    return action

In [12]:

desc = [['S', 'F', 'F'], ['F', 'H', 'H'], ['F', 'F', 'G']]
env = load_frozen_lake(desc=desc)
Q = q_init(env)
Q[7] = np.array([0.5, 0.7, 1, -1])
np.random.seed(0)
print(epsilon_greedy(Q, 7, 0.5))
np.random.seed(1)
print(epsilon_greedy(Q, 7, 0.5))

2
2


In [55]:
def train(env, Q, episodes=5000, max_steps=100,
          alpha=0.1, gamma=0.99, epsilon=1,
          min_epsilon=0.1, epsilon_decay=0.05):
    """Train agent to learn Q-values."""
    total_rewards = []

    for episode in range(episodes):
        state = env.reset()
        if isinstance(state, tuple):
            state = state[0]
        rewards = 0
        for step in range(max_steps):
            action = epsilon_greedy(Q, state, epsilon)
            
            output = env.step(action)
            print("Output:", output)  # Debugging line
            
            new_state, reward, done, _, _ = output  # Adjusted unpacking
            
            if isinstance(new_state, tuple):
                new_state = new_state[0]
            
            if done and reward == 0:
                reward = -1

            # Update Q-table for Q(s,a)
            Q[state, action] = (1 - alpha) * Q[state, action] + \
            alpha * (reward + gamma * np.max(Q[new_state, :]))

            state = new_state
            rewards += reward  # Accumulate rewards

            if done:
                break

        # Exploration rate decay
        epsilon = min_epsilon + (1 - min_epsilon) * np.exp(-epsilon_decay * episode)

        total_rewards.append(rewards)  # Append the total reward of this episode

    return Q, total_rewards





In [56]:
print(Q)
np.random.seed(0)
desc = [['S', 'F', 'F'], ['F', 'H', 'H'], ['F', 'F', 'G']]
env = load_frozen_lake(desc=desc)
Q = q_init(env)
print(Q)
Q, total_rewards  = train(env, Q)
print(Q)
split_rewards = np.split(np.array(total_rewards), 10)
for i, rewards in enumerate(split_rewards):
    print((i+1) * 500, ':', np.mean(rewards))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Output: (3, 0.0, False, False, {'prob': 1.0})
Output: (3, 0.0, False, False, {'prob': 1.0})
Output: (0, 0.0, False, False, {'prob': 1.0})
Output: (0, 0.0, False, False, {'prob': 1.0})
Output: (1, 0.0, False, False, {'prob': 1.0})
Output: (0, 0.0, False, False, {'prob': 1.0})
Output: (0, 0.0, False, False, {'prob': 1.0})
Output: (3, 0.0, False, False, {'prob': 1.0})
Output: (6, 0.0, False, False, {'prob': 1.0})
Output: (7, 0.0, False, False, {'prob': 1.0})
Output: (4, 0.0, True, False, {'prob': 1.0})
Output: (3, 0.0, False, False, {'prob': 1.0})
Output: (6, 0.0, False, False, {'prob': 1.0})
Output: (7, 0.0, False, False, {'prob': 1.0})
Output: (7, 0.0, False, False, {'prob': 1.0})
Output: (6, 0.0, False, False, {'prob':

In [58]:
# Initialize the environment and Q-table as you did before
env = load_frozen_lake(desc=desc)
Q = q_init(env)

# Reset the environment to get the initial state
initial_state = env.reset()

# Choose an action (for testing purposes, let's choose 0)
action = 0

# Now, try running the step function and print its output
output = env.step(action)
print("Output of env.step(action):", output)


Output of env.step(action): (0, 0.0, False, False, {'prob': 1.0})


In [59]:
np.random.seed(0)
desc = [['S', 'F', 'F'], ['F', 'H', 'H'], ['F', 'F', 'G']]
env = load_frozen_lake(desc=desc)
Q = q_init(env)

Q, total_rewards  = train(env, Q)
print(Q)
split_rewards = np.split(np.array(total_rewards), 10)
for i, rewards in enumerate(split_rewards):
    print((i+1) * 500, ':', np.mean(rewards))

Output: (3, 0.0, False, False, {'prob': 1.0})
Output: (6, 0.0, False, False, {'prob': 1.0})
Output: (6, 0.0, False, False, {'prob': 1.0})
Output: (3, 0.0, False, False, {'prob': 1.0})
Output: (4, 0.0, True, False, {'prob': 1.0})
Output: (0, 0.0, False, False, {'prob': 1.0})
Output: (0, 0.0, False, False, {'prob': 1.0})
Output: (0, 0.0, False, False, {'prob': 1.0})
Output: (0, 0.0, False, False, {'prob': 1.0})
Output: (0, 0.0, False, False, {'prob': 1.0})
Output: (1, 0.0, False, False, {'prob': 1.0})
Output: (1, 0.0, False, False, {'prob': 1.0})
Output: (0, 0.0, False, False, {'prob': 1.0})
Output: (0, 0.0, False, False, {'prob': 1.0})
Output: (1, 0.0, False, False, {'prob': 1.0})
Output: (1, 0.0, False, False, {'prob': 1.0})
Output: (2, 0.0, False, False, {'prob': 1.0})
Output: (1, 0.0, False, False, {'prob': 1.0})
Output: (4, 0.0, True, False, {'prob': 1.0})
Output: (0, 0.0, False, False, {'prob': 1.0})
Output: (0, 0.0, False, False, {'prob': 1.0})
Output: (0, 0.0, False, False, {'pro

In [60]:
def play(env, Q, max_steps=100):
    """Play agent with learned Q-values."""
    state = env.reset()
    total_rewards = 0
    for step in range(max_steps):
        action = np.argmax(Q[state])
        new_state, reward, done, info = env.step(action)
        env.render()
        state = new_state
        total_rewards += reward
        if done:
            break
    return total_rewards

In [61]:
# Print updated Q-table
print("\n\n********Q-table********\n")
print(Q)




********Q-table********

[[ 0.96059389  0.970299    0.95096644  0.96059418]
 [ 0.96059421 -0.86491483  0.21094812  0.25747545]
 [ 0.58120893 -0.271       0.          0.        ]
 [ 0.97029857  0.9801     -1.          0.96059587]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.98009969  0.98009994  0.99        0.97029762]
 [ 0.98009969  0.98999605  1.         -0.99999325]
 [ 0.          0.          0.          0.        ]]
